#!/bin/bash 

if [ "$1" == "" ]; then
    echo "Genterate create-file-script from file"
    echo "Usage: "`basename $0`" <file>"
    exit
fi

clrB="\033[01;36m"
clrE="\033[00m"

echo -e "${clrB}-----[ copy it ]--------------------------------${clrE}"
echo "echo '`gzip -c $1 | base64`' | base64 -d | gunzip > $1"
echo "chmod `stat --format=%a $1` $1"
echo "if [ \`md5sum $1 | cut -d \" \" -f 1\` == \"`md5sum $1 | cut -d \" \" -f 1`\" ];"
echo "then echo \"md5 OK\"; else echo \"md5 FAIL\"; fi"
echo -e "${clrB}-----[ /copy it ]-------------------------------${clrE}"
